### 팔로우 등록
POST http://localhost:8083/follow/stores/9
Content-Type: application/json
Authorization: {{user1Auth}}


### 팔로우 취소
DELETE http://localhost:8083/follow/stores/1
Content-Type: application/json
Authorization: {{user1Auth}}

### 팔로우 카페 조회
GET http://localhost:8082/follow/stores
Content-Type: application/json
Authorization: {{user1Auth}}

