### 예약 등록
POST http://localhost:8085/reservations
Content-Type: application/json
Authorization: {{user1Auth}}

{
  "themeTimeId": 1,
  "player": 4,
  "price": 50000,
  "paymentStatus": "COMPLETE"
}

### 예약 취소
DELETE http://localhost:8085/reservations/65
Content-Type: application/json
Authorization: {{user1Auth}}

### 예약 내역 조회
GET http://localhost:8085/reservations
Content-Type: application/json
Authorization: {{user1Auth}}



