### 카카오페이 호출
POST http://localhost:8089/payment/prepare/1
Authorization: {{user1Auth}}
Content-Type: application/json

### 회원가입 요청
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "name": "박세미",
  "email": "tpal0719@naver.com",
  "password": "Test1234!"
}

### 로그인 요청
POST http://localhost:8080/users/login
Content-Type: application/json


{
  "email": "tpal0719@naver.com",
  "password": "Test1234!"
}
> {% client.global.set("user1Auth", response.headers.valueOf("Authorization")); %}