### 예약 생성
POST http://localhost:8086/reservations
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "themeTimeId": 2,
  "player": 4,
  "price": 30000,
  "paymentStatus": "COMPLETE"
}

### 특정 테마의 예약 전체 조회
GET http://localhost:8088/manager/stores/themes/reservations/
Authorization: {{manager1Auth}}

### 예약 강제 취소
DELETE http://localhost:8088/manager/stores/themes/reservations/2
Authorization: {{manager1Auth}}