### 회원가입 요청
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "name": "김윤재",
  "email": "ata01@naver.com",
  "password": "Test1234!"
}

### 로그인 요청
POST http://localhost:8080/users/login
Content-Type: application/json


{
  "email": "ata01@naver.com",
  "password": "Test1234!"
}
> {% client.global.set("user1Auth", response.headers.valueOf("Authorization")); %}

### 매니저 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "mmarland0@facebook.com",
  "password": "Test1234!"
}
> {% client.global.set("manager1Auth", response.headers.valueOf("Authorization")); %}


### 관리자 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "admin@joomla.org",
  "password": "Test1234!"
}
> {% client.global.set("adminAuth", response.headers.valueOf("Authorization")); %}