### 매니저 회원가입 (temp code)
POST http://localhost:8080/users/signup/manager

### 매니저 로그인 (temp code)
POST http://localhost:8080/users/login

{
  "email": "manager@email.com",
  "password": "Test1234!"
}

> {% client.global.set("manager1Auth", response.headers.valueOf("Authorization")); %}

### 어드민 회원가입 (temp code)
POST http://localhost:8080/users/signup/admin


### 어드민 로그인 (temp code)
POST http://localhost:8080/users/login

{
  "email": "admin@email.com",
  "password": "Test1234!"
}
> {% client.global.set("admin1Auth", response.headers.valueOf("Authorization")); %}



### ====================================================================================


### 회원가입 요청
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "name": "박세미",
  "email": "tpal0719@naver.com",
  "password": "Test1234!"
}

### 로그인 요청
POST http://localhost:8080/users/login
Content-Type: application/json


{
  "email": "tpal0719@naver.com",
  "password": "Test1234!"
}
> {% client.global.set("user1Auth", response.headers.valueOf("Authorization")); %}

### Email Certification Request
POST http://localhost:8080/users/mail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLquYDsnKTsnqwiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTcyMTgxNjM1NCwiaWF0IjoxNzIxODE0NTU0fQ.rZ7usKXj_0i4xcnmn1x4AsboxSKY8WN_WgdDZMPDC2w




### 매니저 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "manager@email.com",
  "password": "Test1234!"
}
> {% client.global.set("manager1Auth", response.headers.valueOf("Authorization")); %}


### 관리자 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "admin@joomla.org",
  "password": "Test1234!"
}
> {% client.global.set("adminAuth", response.headers.valueOf("Authorization")); %}

### 팔로우 요청
DELETE http://localhost:8083/follow/stores/6
Content-Type: application/json
Authorization: {{user1Auth}}

